# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 200


obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# reset parameters
use_reset : True 
reset_every : 600000
num_resets : 6
reset_components : ["mixer", "target_mixer", "agent", "target_agent"]
reset_mode : 'last'
# the parameter below is not implemented and used since it is not used in the primacy bias paper (need to add offline updates to use this)
# reset_offset : 0
# num_updates_on_reset : 1

# use the Q_Learner to train
standardise_returns: False
standardise_rewards: True

agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "qmix"
use_rnn: False
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "qmix"
