env_name : 'Overcooked_asym_advantages'
algo : 'idqn'
lr : 0.0005
batch_size : 32
gamma : 0.99
buffer_limit : 50000
log_interval : 20
max_updates : 30000
max_epsilon : 0.9
min_epsilon : 0.1
test_episodes : 5
warm_up_steps : 2000
update_iter : 10
env_configs: {time_limit: 500,
              env : 'asymmetric_advantages'
}