env_name : 'Switch2-v1'
algo : 'qmix'
lr : 0.001
batch_size : 32
gamma : 0.99
buffer_limit : 50000
log_interval : 20
max_updates : 100000
max_epsilon : 0.9
min_epsilon : 0.1
test_episodes : 5
warm_up_steps : 2000
update_iter : 10
chunk_size : 10
update_target_interval : 20
recurrent: False
env_configs: {time_limit: 30
}